### ISSUE TITLE
Be able to scan in both landscape and portrait

### ISSUE THREAD

**Issue by JohnMcLear** [mclear/my#9]
https://github.com/phonegap/phonegap-plugins/issues/238

**Comment by karlwhite** [comment]
+1 :)

**Comment by ghost** [comment]
:+1:  :-D !

**Comment by JohnMcLear** [comment]
Why are you +1'ing and upvoting on this thread? :) This is for a separate app for reading barcodes and writing their content to nfc tags

**Comment by karlwhite** [comment]
Hmm... that's odd... I swear I arrived here from the issue list for the Barcode Scanner plugin for Phonegap. My apologies!

Edit: I see my mistake. I must have blindly clicked on your link at the bottom of this issue page: https://github.com/phonegap/phonegap-plugins/issues/238

**Comment by ghost** [comment]
Hi John - I followed your link from here : https://github.com/phonegap/phonegap-plugins/issues/238

**Comment by JohnMcLear** [comment]
@dalips @buncle that is just a reference, this is a separate issue on a separate repo

**Comment by karlwhite** [comment]
Yeah, I see that now :) I think I was pretty sleep deprived when I was trying to implement the plugin. Sorry for the confusion :)

**Comment by ghost** [comment]
Ah OK, fair enough :-)
